// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("MBrace.Azure")>]
[<assembly: AssemblyCompanyAttribute("@mbraceproject")>]
[<assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies and other contributors.")>]
[<assembly: AssemblyTrademarkAttribute("MBrace")>]
[<assembly: AssemblyMetadataAttribute("Release Signature","Version 1.5.3, Git Hash 3ad1b4, Build Date 31102017 03:51 -04:00")>]
[<assembly: AssemblyVersionAttribute("1.5.3")>]
[<assembly: AssemblyFileVersionAttribute("1.5.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "MBrace.Azure"
    let [<Literal>] AssemblyCompany = "@mbraceproject"
    let [<Literal>] AssemblyCopyright = "© Nessos Information Technologies and other contributors."
    let [<Literal>] AssemblyTrademark = "MBrace"
    let [<Literal>] AssemblyMetadata_Release_Signature = "Version 1.5.3, Git Hash 3ad1b4, Build Date 31102017 03:51 -04:00"
    let [<Literal>] AssemblyVersion = "1.5.3"
    let [<Literal>] AssemblyFileVersion = "1.5.3"

    let [<Literal>] ReleaseTag = "1.5.3"
