// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyProductAttribute("MBrace.Azure")>]
[<assembly: AssemblyCompanyAttribute("Nessos Information Technologies")>]
[<assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")>]
[<assembly: AssemblyTrademarkAttribute("MBrace")>]
[<assembly: AssemblyMetadataAttribute("Release Signature","Version 1.4.3, Git Hash a5dc0a, Build Date 08062017 12:51 +01:00")>]
[<assembly: AssemblyVersionAttribute("1.4.3")>]
[<assembly: AssemblyFileVersionAttribute("1.4.3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyProduct = "MBrace.Azure"
    let [<Literal>] AssemblyCompany = "Nessos Information Technologies"
    let [<Literal>] AssemblyCopyright = "© Nessos Information Technologies."
    let [<Literal>] AssemblyTrademark = "MBrace"
    let [<Literal>] AssemblyMetadata_Release_Signature = "Version 1.4.3, Git Hash a5dc0a, Build Date 08062017 12:51 +01:00"
    let [<Literal>] AssemblyVersion = "1.4.3"
    let [<Literal>] AssemblyFileVersion = "1.4.3"

    let [<Literal>] ReleaseTag = "1.4.3"
