// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MBrace.Azure")]
[assembly: AssemblyProductAttribute("MBrace.Azure")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyMetadataAttribute("Release Signature","Version 0.7.0, Git Hash 2f8a70, Build Date 28072015 11:55 +03:00")]
[assembly: AssemblyVersionAttribute("0.7.0")]
[assembly: AssemblyFileVersionAttribute("0.7.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.7.0";
    }
}
