// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MBrace.Azure")]
[assembly: AssemblyProductAttribute("MBrace.Azure")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyMetadataAttribute("Release Signature","Version 0.15.2, Git Hash 510589, Build Date 23102015 09:56 +03:00")]
[assembly: AssemblyVersionAttribute("0.15.2")]
[assembly: AssemblyFileVersionAttribute("0.15.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.15.2";
    }
}
