// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MBrace.Azure")]
[assembly: AssemblyProductAttribute("MBrace.Azure")]
[assembly: AssemblyCompanyAttribute("Nessos Information Technologies")]
[assembly: AssemblyCopyrightAttribute("© Nessos Information Technologies.")]
[assembly: AssemblyTrademarkAttribute("MBrace")]
[assembly: AssemblyMetadataAttribute("Release Signature","Version 0.13.1, Git Hash bdec55, Build Date 16102015 16:09 +03:00")]
[assembly: AssemblyVersionAttribute("0.13.1")]
[assembly: AssemblyFileVersionAttribute("0.13.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.13.1";
    }
}
